<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>CyberSecurityChatbotPart2</AssemblyName>
    <RootNamespace>CyberSecurityChatbotPart2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\welcome.wav" />
    <None Remove="Assets\ascii-logo.png" />
    <Content Include="Assets\welcome.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\ascii-logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
